from pydantic import BaseModel, Field

# Schema for Sub-Questions
class SubQuestionSchema(BaseModel):
    sub_questions: list[str] = Field(..., description="List of sub-questions generated by the LLM.")

# Schema for Paragraph Structure
class ParagraphSchema(BaseModel):
    section: str = Field(..., description="The section or paragraph title.")
    purpose: str = Field(..., description="The purpose of this section.")
    evidence_needed: str = Field(..., description="The evidence required to support this section.")
    argument_development: str = Field(..., description="The method of developing the argument in this section.")

# Schema for Essay Structure
class EssayStructureSchema(BaseModel):
    essay_structure: list[ParagraphSchema] = Field(..., description="List of paragraphs that structure the essay.")
